In [143]:
import numpy as np
from scipy.stats import norm, uniform
import statsmodels.api as sm

## T-test для оценки разницы средних в двух выборках
H0: мат. ожидание выборки x равняется мат. ожиданию выборки y 

Альтернативная гипотеза варьируется (больше, меньше, two-tailed)

Дисперсии выборок заранее известны и равны

In [145]:
std = 1
n = 100

In [146]:
min_ = -0.5
max_ = 0.5
mu_x = uniform.rvs(size=1, loc=min_, scale=max_-min_) 
mu_y = uniform.rvs(size=1, loc=min_, scale=max_-min_) 
x = norm.rvs(size = n, loc = mu_x, scale = std)
y = norm.rvs(size = n, loc = mu_y, scale = std)

In [147]:
mu_x, mu_y

(array([-0.12545988]), array([0.45071431]))

In [148]:
# в функции ttest_ind() по умолчанию дисперсии равны

res = sm.stats.ttest_ind(x, y)
print("Two Sample t-test")
print("t =", res[0])
print("p-value =", res[1])
print("df = ", res[2])

Two Sample t-test
t = -5.717700441584866
p-value = 3.932612870603071e-08
df =  198.0


## T-test для оценки разницы средних в двух выборках
Дисперсии выборок неизвестны (модификация Уэлша)

In [149]:
np.random.seed(17)

In [150]:
std_x = uniform.rvs(size=1, loc=0, scale=3) 
std_y = uniform.rvs(size=1, loc=0, scale=3) 

In [151]:
std_x

array([0.88399501])

In [152]:
std_y

array([1.59176027])

In [153]:
n = 100
min_ = -0.5
max_ = 0.5
mu_x = uniform.rvs(size=1, loc=min_, scale=max_-min_) 
mu_y = uniform.rvs(size=1, loc=min_, scale=max_-min_) 
x = norm.rvs(size = n, loc = mu_x, scale = std_x)
y = norm.rvs(size = n, loc = mu_y, scale = std_y)

In [154]:
# t-тест с одинаковыми дисперсиями
# по-умолчанию usevar="pooled" и означает одинаковые дисперсии
# поэтому в явном виде писать не требуется
res = sm.stats.ttest_ind(x, y, usevar="pooled") 

print("Two Sample t-test")
print("t =", res[0])
print("p-value =", res[1])
print("df = ", res[2])

Two Sample t-test
t = 0.9992076091946488
p-value = 0.3189136938843909
df =  198.0


Продемонстрируем разницу между обычным t-тестом и модификацией Уэлша

In [155]:
# t-тест с разными дисперсиями
res = sm.stats.ttest_ind(x, y, usevar="unequal")
print("Two Sample t-test")
print("t =", res[0])
print("p-value =", res[1])
print("df = ", res[2])

Two Sample t-test
t = 0.9992076091946487
p-value = 0.31913591304533245
df =  167.44395195850868


Различия незначительны

Но на малых количествах данных, если дисперсии неизвестны, лучше придерживаться двухвыборочной модификации Уэлша

А теперь вспомним, что t.test можно использовать только на нормальном распределении

В прошлом результате p.value = 0.8. Что если мы добавим пару выбросов? 

In [156]:
x = np.append(x,[10,50])

Получим p-value в два раза меньше 

In [157]:
res = sm.stats.ttest_ind(x, y)
print("Two Sample t-test")
print("p-value =", res[1])

Two Sample t-test
p-value = 0.15100502632471677


Мы все равно не можем отвергнуть нулевую гипотезу на 95% уровне значимости, но суть в том, что ttest весьма чувствителен к выбросам и про это нельзя забывать